add hm-1
dramaretskiy/homeworks-angular-pavel-dramaretskiy pull request #1
Opened 2019-07-04 11:18 UTC by dramaretskiy

2019-07-04 11:43 UTC, soulr1ver commented on homework-1/ts/script.ts
> +function factorial(value: number): number {
что если value < 0?

2019-07-04 11:45 UTC, soulr1ver commented on homework-1/ts/script.ts
> +  let i: number;
лучше вынести определение данной переменной в цикл, так как кроме цикла ты её нигде больше не используешь

2019-07-04 11:48 UTC, soulr1ver commented on homework-1/ts/script.ts
> +function fibonacci(number: number): Array<number> {
если в функцию передать -1 - есть результат. с отрицательным значениями данная функция не должна работать

2019-07-04 11:52 UTC, soulr1ver requested changes
bugs

2019-07-08 08:23 UTC, dramaretskiy commented on homework-1/ts/script.ts
> +  let i: number;
Если вынести определение в цикл, то переменная будет распознаваться только в теле цикла, а в условие цикла "i" не будет видно.

2019-07-08 09:36 UTC, soulr1ver approved these changes

2019-07-08 09:37 UTC, merged